const { contextBridge, ipcRenderer } = require('electron');
console.log('[Preload] Loaded — queue:started + queue:enqueued channels active');

contextBridge.exposeInMainWorld('electron', {
  ipcRenderer: {
    send: (channel, data) => {
      const validChannels = [
        'prompt-capture:hide',
        'prompt-capture:resize',
        'prompt-capture:move',
        'prompt-capture:pick-file',
        'results-window:show',
        'results-window:close',
        'results-window:resize',
        'results-window:move',
        'results-window:set-prompt',
        'results-window:show-error',
        'ws-bridge:send-message',
        'ws-bridge:connect',
        'stategraph:process',
        'shell:open-path',
        'shell:open-url',
        'install:confirm',
        'guide:continue',
        'guide:cancel',
        'schedule:dismiss',
        'automation:cancel',
        'voice:start',
        'voice:stop',
        'voice:push-to-talk-start',
        'voice:push-to-talk-end',
        'voice:audio-chunk',
        'voice:transcript-direct',
        'voice:companion-open',
        'voice:companion-close',
        'skill:list',
        'skill:delete',
        'skill:store-open',
        'skill:build-start',
        'skill:build-answer',
        'ptt:input-focus',
        'ptt:input-blur',
        'ptt:keyup',
        'queue:submit',
        'queue:rerun',
        'queue:cancel',
        'cron:toggle',
        'cron:delete',
        'cron:run-now',
        'cron:list',
        'skills:list',
        'skills:save-secret',
        'skills:open-code',
        'skills:upload',
        'skills:oauth-connect',
        'skills:update-oauth-scopes',
        'skills:delete',
        'skills:reveal-secret',
        'gather:answer',
        'gather:credential',
        'gather:oauth_connect',
        'gather:oauth_skip',
        'connections:list',
        'connections:connect',
        'connections:disconnect',
        'prompt-queue:submit',
        'prompt-queue:cancel',
        'prompt-queue:dismiss-alert',
      ];
      if (validChannels.includes(channel)) {
        ipcRenderer.send(channel, data);
      }
    },
    on: (channel, func) => {
      const validChannels = [
        'prompt-capture:show',
        'prompt-capture:capture-screenshot',
        'prompt-capture:screenshot-result',
        'results-window:show',
        'prompt-capture:add-highlight',
        'results-window:set-prompt',
        'results-window:display-error',
        'ws-bridge:connected',
        'ws-bridge:disconnected',
        'ws-bridge:message',
        'ws-bridge:error',
        'automation:progress',
        'schedule:pending',
        'bridge:status',
        'voice:status',
        'voice:speaking',
        'voice:listening',
        'voice:transcript',
        'voice:response',
        'voice:error',
        'voice:inject-prompt',
        'voice:companion-closed',
        'skill:list-response',
        'skill:delete-response',
        'skill:store-trigger',
        'skill:build-done',
        'skill:build-asking',
        'voice:ptt-start',
        'voice:ptt-stop',
        'ptt:transcript',
        'queue:update',
        'queue:started',
        'queue:enqueued',
        'cron:update',
        'skills:update',
        'connections:update',
        'gather:pending',
        'prompt-queue:update',
        'prompt-queue:restart-alert',
        'prompt-queue:restart-cancel',
        'skills:secret-revealed',
        'reminder:play-sound',
      ];
      if (validChannels.includes(channel)) {
        ipcRenderer.on(channel, func);
      }
    },
    removeAllListeners: (channel) => {
      const validChannels = [
        'prompt-capture:show',
        'prompt-capture:add-highlight',
        'prompt-capture:capture-screenshot',
        'prompt-capture:screenshot-result',
        'results-window:show',
        'results-window:set-prompt',
        'results-window:display-error',
        'ws-bridge:connected',
        'ws-bridge:disconnected',
        'ws-bridge:message',
        'ws-bridge:error',
        'automation:progress',
        'schedule:pending',
        'bridge:status',
        'voice:status',
        'voice:speaking',
        'voice:listening',
        'voice:transcript',
        'voice:response',
        'voice:error',
        'voice:inject-prompt',
        'voice:companion-closed',
        'skill:list-response',
        'skill:delete-response',
        'skill:store-trigger',
        'skill:build-done',
        'skill:build-asking',
        'voice:ptt-start',
        'voice:ptt-stop',
        'ptt:transcript',
        'queue:update',
        'queue:started',
        'queue:enqueued',
        'cron:update',
        'skills:update',
        'connections:update',
        'gather:pending',
        'prompt-queue:update',
        'prompt-queue:restart-alert',
        'prompt-queue:restart-cancel',
        'skills:secret-revealed',
        'reminder:play-sound',
      ];
      if (validChannels.includes(channel)) {
        ipcRenderer.removeAllListeners(channel);
      }
    },
    removeListener: (channel, func) => {
      const validChannels = [
        'prompt-capture:show',
        'prompt-capture:add-highlight',
        'prompt-capture:capture-screenshot',
        'prompt-capture:screenshot-result',
        'results-window:show',
        'results-window:set-prompt',
        'results-window:display-error',
        'ws-bridge:connected',
        'ws-bridge:disconnected',
        'ws-bridge:message',
        'ws-bridge:error',
        'automation:progress',
        'schedule:pending',
        'bridge:status',
        'voice:status',
        'voice:speaking',
        'voice:listening',
        'voice:transcript',
        'voice:response',
        'voice:error',
        'voice:inject-prompt',
        'voice:companion-closed',
        'skill:list-response',
        'skill:delete-response',
        'skill:store-trigger',
        'skill:build-done',
        'skill:build-asking',
        'voice:ptt-start',
        'voice:ptt-stop',
        'ptt:transcript',
        'queue:update',
        'queue:started',
        'queue:enqueued',
        'cron:update',
        'skills:update',
        'connections:update',
        'gather:pending',
        'prompt-queue:update',
        'prompt-queue:restart-alert',
        'prompt-queue:restart-cancel',
        'skills:secret-revealed',
        'reminder:play-sound',
      ];
      if (validChannels.includes(channel)) {
        ipcRenderer.removeListener(channel, func);
      }
    },
    invoke: (channel, data) => {
      // const validChannels = ['capture-screenshot'];
      // if (validChannels.includes(channel)) {
      //   return ipcRenderer.invoke(channel, data);
      // }
    },
  },
});
