const { contextBridge, ipcRenderer } = require('electron');
console.log('[Preload] Loaded — queue:started + queue:enqueued channels active');

// Token-based listener tracking: prevents duplicate listeners across React StrictMode
// remounts. contextBridge wraps functions on every boundary crossing so function
// reference equality never works — we use a string token instead.
// channel → Map<token, wrapped>
const _wiredListeners = new Map();

contextBridge.exposeInMainWorld('electron', {
  ipcRenderer: {
    send: (channel, data) => {
      const validChannels = [
        'prompt-capture:hide',
        'prompt-capture:resize',
        'prompt-capture:move',
        'prompt-capture:pick-file',
        'window:hide',
        'window:resize',
        'window:smart-resize',
        'window:move',
        'file-drop',
        'dialog:open-file',
        'results-window:show',
        'results-window:close',
        'results-window:resize',
        'results-window:move',
        'unified:set-prompt',
        'results-window:show-error',
        'unified:resize-window',
        'ws-bridge:send-message',
        'ws-bridge:connect',
        'stategraph:process',
        'shell:open-path',
        'shell:open-url',
        'install:confirm',
        'guide:continue',
        'guide:cancel',
        'schedule:dismiss',
        'automation:cancel',
        'voice:start',
        'voice:stop',
        'voice:push-to-talk-start',
        'voice:push-to-talk-end',
        'voice:audio-chunk',
        'voice:transcript-direct',
        'voice:companion-open',
        'voice:companion-close',
        'skill:list',
        'skill:delete',
        'skill:store-open',
        'skill:build-start',
        'skill:build-answer',
        'ptt:input-focus',
        'ptt:input-blur',
        'ptt:keyup',
        'queue:submit',
        'queue:rerun',
        'queue:cancel',
        'cron:toggle',
        'cron:delete',
        'cron:run-now',
        'cron:list',
        'skills:list',
        'skills:save-secret',
        'skills:open-code',
        'skills:upload',
        'skills:oauth-connect',
        'skills:update-oauth-scopes',
        'skills:delete',
        'skills:reveal-secret',
        'gather:answer',
        'gather:credential',
        'gather:oauth_connect',
        'gather:oauth_skip',
        'connections:list',
        'connections:connect',
        'connections:disconnect',
        'prompt-queue:submit',
        'prompt-queue:cancel',
        'prompt-queue:dismiss-alert',
        'prompt-queue:resume-pending',
        'plan:approve',
        'plan:cancel',
        'plan:new',
        'plan:rescan',
        'plan:open-editor',
        'agents:list',
        'agents:create',
        'agents:learn',
        'agents:learn-cancel',
        'agents:train',
        'agents:delete',
        'agents:test-skill',
        'agents:publish-skill',
        'agents:delete-skill',
      ];
      if (validChannels.includes(channel)) {
        ipcRenderer.send(channel, data);
      }
    },
    on: (channel, func, token) => {
      const validChannels = [
        'prompt-capture:show',
        'prompt-capture:capture-screenshot',
        'prompt-capture:screenshot-result',
        'results-window:show',
        'prompt-capture:add-highlight',
        'unified:set-prompt',
        'unified:clear',
        'results-window:display-error',
        'ws-bridge:connected',
        'ws-bridge:disconnected',
        'ws-bridge:message',
        'ws-bridge:error',
        'automation:progress',
        'schedule:pending',
        'bridge:status',
        'voice:status',
        'voice:speaking',
        'voice:listening',
        'voice:transcript',
        'voice:response',
        'voice:error',
        'voice:inject-prompt',
        'voice:companion-closed',
        'skill:list-response',
        'skill:delete-response',
        'skill:store-trigger',
        'skill:build-done',
        'skill:build-asking',
        'voice:ptt-start',
        'voice:ptt-stop',
        'ptt:transcript',
        'queue:update',
        'queue:started',
        'queue:enqueued',
        'cron:update',
        'skills:update',
        'connections:update',
        'gather:pending',
        'prompt-queue:update',
        'prompt-queue:restart-alert',
        'prompt-queue:restart-cancel',
        'skills:secret-revealed',
        'reminder:play-sound',
        'plan:approved',
        'plan:rescanned',
        'plan:error',
        'scan:discovery',
        'app-control:mode-change',
        'cron:list',
        'queue:item-done',
        'connections:list',
        'highlights:update',
        'highlights:available',
        'highlights:confirmed',
        'file-drop:result',
        'skill-build:progress',
        'action-chips',
        'search:sources',
        'window:show',
        'is-streaming',
        'agents:list',
        'agents:new',
        'agents:creating',
        'agents:error',
        'agents:update',
        'agents:learn-progress',
        'agents:train-progress',
        'agents:skill-test-update',
      ];
      if (validChannels.includes(channel)) {
        const wrapped = (_event, ...args) => func(...args);
        if (token) {
          // Token path: deduplicate by token — remove any stale listener first.
          if (!_wiredListeners.has(channel)) _wiredListeners.set(channel, new Map());
          const chMap = _wiredListeners.get(channel);
          const existing = chMap.get(token);
          if (existing) ipcRenderer.removeListener(channel, existing);
          chMap.set(token, wrapped);
        }
        ipcRenderer.on(channel, wrapped);
      }
    },
    removeAllListeners: (channel) => {
      const validChannels = [
        'prompt-capture:show',
        'prompt-capture:add-highlight',
        'prompt-capture:capture-screenshot',
        'prompt-capture:screenshot-result',
        'results-window:show',
        'unified:set-prompt',
        'unified:clear',
        'results-window:display-error',
        'ws-bridge:connected',
        'ws-bridge:disconnected',
        'ws-bridge:message',
        'ws-bridge:error',
        'automation:progress',
        'schedule:pending',
        'bridge:status',
        'voice:status',
        'voice:speaking',
        'voice:listening',
        'voice:transcript',
        'voice:response',
        'voice:error',
        'voice:inject-prompt',
        'voice:companion-closed',
        'skill:list-response',
        'skill:delete-response',
        'skill:store-trigger',
        'skill:build-done',
        'skill:build-asking',
        'voice:ptt-start',
        'voice:ptt-stop',
        'ptt:transcript',
        'queue:update',
        'queue:started',
        'queue:enqueued',
        'cron:update',
        'skills:update',
        'connections:update',
        'gather:pending',
        'prompt-queue:update',
        'prompt-queue:restart-alert',
        'prompt-queue:restart-cancel',
        'skills:secret-revealed',
        'reminder:play-sound',
        'plan:approved',
        'plan:rescanned',
        'plan:error',
      ];
      if (validChannels.includes(channel)) {
        ipcRenderer.removeAllListeners(channel);
        _wiredListeners.delete(channel);
      }
    },
    removeListenerByToken: (channel, token) => {
      const validChannels = [
        'ws-bridge:message',
        'unified:set-prompt',
        'unified:clear',
        'automation:progress',
        'is-streaming',
        'queue:update',
        'queue:item-done',
        'cron:list',
        'cron:update',
        'skills:list',
        'connections:list',
        'prompt-queue:update',
        'prompt-queue:restart-alert',
        'highlights:update',
        'highlights:available',
        'highlights:confirmed',
        'voice:inject-prompt',
        'voice:response',
        'voice:recording-started',
        'voice:recording-stopped',
        'file-drop:result',
        'skill-build:progress',
        'install:confirm',
        'schedule:pending',
        'bridge:status',
        'scan:progress',
        'scan:discovery',
        'app-control:mode-change',
        'plan:approved',
        'action-chips',
        'search:sources',
        'window:show',
        'gather:pending',
        'queue:enqueued',
        'prompt-capture:show',
        'ws-bridge:connected',
        'ws-bridge:disconnected',
        'ws-bridge:error',
        'queue:started',
        'agents:list',
        'agents:new',
        'agents:creating',
        'agents:error',
        'agents:update',
      ];
      if (validChannels.includes(channel)) {
        const chMap = _wiredListeners.get(channel);
        if (chMap && token) {
          const wrapped = chMap.get(token);
          if (wrapped) {
            ipcRenderer.removeListener(channel, wrapped);
            chMap.delete(token);
          }
        }
      }
    },
    removeListener: (channel, func) => {
      const validChannels = [
        'prompt-capture:show',
        'prompt-capture:add-highlight',
        'prompt-capture:capture-screenshot',
        'prompt-capture:screenshot-result',
        'results-window:show',
        'unified:set-prompt',
        'unified:clear',
        'results-window:display-error',
        'ws-bridge:connected',
        'ws-bridge:disconnected',
        'ws-bridge:message',
        'ws-bridge:error',
        'automation:progress',
        'schedule:pending',
        'bridge:status',
        'voice:status',
        'voice:speaking',
        'voice:listening',
        'voice:transcript',
        'voice:response',
        'voice:error',
        'voice:inject-prompt',
        'voice:companion-closed',
        'skill:list-response',
        'skill:delete-response',
        'skill:store-trigger',
        'skill:build-done',
        'skill:build-asking',
        'voice:ptt-start',
        'voice:ptt-stop',
        'ptt:transcript',
        'queue:update',
        'queue:started',
        'queue:enqueued',
        'cron:update',
        'skills:update',
        'connections:update',
        'gather:pending',
        'prompt-queue:update',
        'prompt-queue:restart-alert',
        'prompt-queue:restart-cancel',
        'skills:secret-revealed',
        'reminder:play-sound',
        'plan:approved',
        'plan:rescanned',
        'plan:error',
        'agents:list',
        'agents:new',
        'agents:creating',
        'agents:error',
        'agents:update',
        'agents:learn-progress',
        'agents:train-progress',
      ];
      if (validChannels.includes(channel)) {
        // Legacy path: func-reference removal won't work across contextBridge.
        // Use removeListenerByToken instead when possible.
      }
    },
    invoke: (channel, data) => {
      // const validChannels = ['capture-screenshot'];
      // if (validChannels.includes(channel)) {
      //   return ipcRenderer.invoke(channel, data);
      // }
    },
  },
});
